[project]
name = "toiny-lm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tokenizers>=0.21.4",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
    "numpy>=1.24.0",
    "datasets>=3.0.0",
]
